version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.4.4
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    resource_class: medium
    docker:
      - image: "cypress/browsers:node16.13.0-chrome95-ff94"
jobs:
  build_success:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "sending slack notification"
      - slack/notify:
          branch_pattern: dev
          mentions: '<@U02F5S5T0F3>'
          template: basic_success_1
          event: pass
workflows:
  build_and_deploy:
    jobs:
      - cypress/install:
          yarn: true
          executor: with-chrome
          build: yarn install
          filters:
            branches:
              only:
                - master
                - dev
                - testing
      - cypress/run:
          name: cypress/staging/auth
          requires:
            - cypress/install
          context:
            - Slack
            - Staging
          filters:
            branches:
              only:
                - testing
                - dev
          no-workspace: true
          yarn: true
          executor: with-chrome
          config-file: staging-config.json
          tags: 'staging'
          parallel: true
          parallelism: 3
          spec: cypress/integration/0-auth/*
          group: Auth Flow
          post-steps:
            - store_test_results:
                path: cypress/results/0-auth
            - slack/notify:
                branch_pattern: 'dev'
                mentions: '<@U02F5S5T0F3>'
                template: basic_fail_1
                event: fail
      - cypress/run:
          name: cypress/staging/orders
          requires:
            - cypress/install
          context:
            - Slack
            - Staging
          filters:
            branches:
              only:
                - testing
                - dev
          no-workspace: true
          yarn: true
          executor: with-chrome
          config-file: staging-config.json
          tags: 'staging'
          parallel: true
          parallelism: 3
          spec: cypress/integration/1-orders/*
          group: Orders
          post-steps:
            - store_test_results:
                path: cypress/results/1-orders
            - slack/notify:
                branch_pattern: 'dev'
                mentions: '<@U02F5S5T0F3>'
                template: basic_fail_1
                event: fail
      - cypress/run:
          name: cypress-production
          requires:
            - cypress/install
          context:
            - Slack
            - Production
          filters:
            branches:
              only:
                - master
          no-workspace: true
          yarn: true
          executor: with-chrome
          config-file: production-config.json
          tags: 'production'
          store_artifacts: true
          parallel: true
          parallelism: 3
          post-steps:
            - slack/notify:
                branch_pattern: master
                mentions: '<@U02F5S5T0F3>'
                template: basic_fail_1
                event: fail
      - build_success:
          context:
            - Slack
          requires:
            - cypress/staging/auth
            - cypress/staging/orders
      - heroku/deploy-via-git:
          name: heroku-deploy/staging
          requires:
            - build_success
          context:
            - Staging
          filters:
            branches:
              only:
                - dev
      - heroku/deploy-via-git:
          name: heroku/deploy-production
          requires:
            - cypress-production
          context:
            - Production
          filters:
            branches:
              only:
                - master