version: 2.1

orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    resource_class: medium
    docker:
      - image: "cypress/browsers:node16.13.0-chrome95-ff94"
workflows:
  build:
    jobs:
      - cypress/run:
          no-workspace: true
          yarn: true
          executor: with-chrome
          config-file: staging-config.json