version: 2.1

orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    resource_class: medium
    docker:
      - image: "cypress/browsers:node16.13.0-chrome95-ff94"
    environment:
      API_KEY: h5tUvrDlLvIBQ3A72Nh2SNA6
workflows:
  build:
    jobs:
      - cypress/install:
          build: yarn build
          filters:
            branches:
              only:
                - master
                - dev
                - testing
      - cypress/run:
          requires:
            - cypress/install
          filters:
            branches:
              only:
                - testing
                - dev
          no-workspace: true
          yarn: true
          executor: with-chrome
          config-file: staging-config.json
          tags: 'staging'
          store_artifacts: true
          parallel: true
          parallelism: 3
      - cypress/run:
          requires:
            - cypress/install
          no-workspace: true
          yarn: true
          executor: with-chrome
          config-file: production-config.json
          tags: 'production'
          store_artifacts: true
          parallel: true
          parallelism: 3
          filters:
            branches:
              only:
                - master