export const jobRequestSchema = {
	pickupFirstName: '',
	pickupLastName: '',
	pickupBusinessName: '',
	pickupAddress: '',
	pickupFormattedAddress: {
		street: '',
		city: '',
		postcode: '',
		countryCode: 'GB',
	},
	pickupEmailAddress: '',
	pickupPhoneNumber: '',
	pickupInstructions: '',
	packagePickupStartTime: '',
	dropoffFirstName: '',
	dropoffLastName: '',
	dropoffBusinessName: '',
	dropoffAddress: '',
	dropoffFormattedAddress: {
		street: '',
		city: '',
		postcode: '',
		country: 'GB',
	},
	dropoffEmailAddress: 'N/A',
	dropoffPhoneNumber: '',
	dropoffInstructions: '',
	packageDropoffStartTime: '',
	packageDescription: '',
	packageDeliveryType: '',
	itemsCount: null,
	vehicleType: '',
};